"""inbox reply

Revision ID: 86ac239b90ca
Revises: 629c1f9e9001
Create Date: 2018-05-13 23:41:29.174123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ac239b90ca'
down_revision = '629c1f9e9001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox', sa.Column('reply_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbox', 'reply_id')
    # ### end Alembic commands ###
