"""empty message

Revision ID: 90150bf578b1
Revises: 86ac239b90ca
Create Date: 2018-05-15 05:34:27.700022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90150bf578b1'
down_revision = '86ac239b90ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_inbox_receiver_id_user'), 'user', ['receiver_id'], ['id'])
        batch_op.drop_column('reply_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_inbox_receiver_id_user'), type_='foreignkey')
        batch_op.drop_column('read')

    # ### end Alembic commands ###
